### ISSUE TITLE
Minor change to readme

### ISSUE THREAD

**Issue by WilfulTravesty** [jfcherng/Sublime-VisualizeZeroWidthChars#1]
**Current**: Go to Menu > Preferences > Package Control > Settings - User

**Correction (for Mac?)**: Go to Menu > Preferences > Package Settings -> Package Control > Settings - User

**Comment by jfcherng** [comment]
Yes, that's a typo. Would you like to send a PR? Or I just fix it? :)

**Comment by jfcherng** [comment]
Fixed in d8bddce. Thank you!

**Comment by WilfulTravesty** [comment]
I wasn't sure if Windows was the same or not, so I didn't make a PR. But I see you resolved it. :)
